name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: cachix/install-nix-action@v10
    - uses: actions/checkout@v2
    - run: nix-build
    - run: ./test.bash
